#Which fluids should be blacklisted? This isn't retroactive.
#Empty by default. Water cannot be blacklisted.
fluid_blacklist = ["oreganized:molten_lead", "supplementaries:lumisene"]
#Which blocks should be blacklisted? This isn't retroactive.
#Only applies to SimpleWaterLoggableBlock variants (stairs, slabs, etc.).
#Remember, flowing fluids and source blocks are blacklisted separately (they're distinct fluids as far as Minecraft is concerned).
block_blacklist = []
#Should fluidlogged blocks emit the higher of blocklight and fluid light?
#Significant performance penalty.
consider_fluid_light = true
#Can partial fluid blocks waterlog
flowing_fluids_log = false
#Can we assume you aren't trying to worldgen blocks logged with non-vanilla fluids? There may be a significant performance penalty if we can't.
explicitly_do_not_support_worldgen = true
#Should we force chunk updates (resolves sync issues, but may cause stability problems)
force_chunk_updates = false
